security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            pattern: ^/

            logout:
                path: logout

            form_login:
                login_path: login
                check_path: login

                form_only: true
                username_parameter: 'login[username]'
                password_parameter: 'login[password]'

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS  }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
